openapi: 3.0.3

info:
  title: Open Hit Game API
  version: 1.0.0

servers:
  - url: /api

paths:
  /lobbies:
    post:
      tags:
        - Lobby
      operationId: createLobby
      summary: Create a new lobby

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLobbyRequestV1Dto'

      responses:
        '200':
          description: Lobby created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateLobbyResponseV1Dto'

components:
  schemas:

    CreateLobbyRequestV1Dto:
      type: object
      properties:
        playerName:
          type: string
      required:
        - playerName

    CreateLobbyResponseV1Dto:
      type: object
      properties:
        joinCode:
          type: string
      required:
        - joinCode