services:
  angular:
    stdin_open: true
    container_name: angular
    build: ./angular
    volumes:
      - ./workDir/frontend:/var/www/frontend/:cached
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - network_infrastructure
    command: ng serve frontend --host 0.0.0.0 --port 4200 --no-hmr
  spring:
    build: spring
    container_name: spring
    tty: true
    command: mvn spring-boot:run
    networks:
      - network_infrastructure
    volumes:
      - ./workDir/backend:/home/spring/:cached
      - ./workDir/logs/:/var/log/nginx/:cached
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:alpine
    container_name: postgres_database
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: dbUser
      POSTGRES_DB: ohg
    volumes:
      - /var/lib/postgresql/
    networks:
      - network_infrastructure
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    links:
      - spring
      - angular
    volumes:
      - ./workDir/backend/:/home/spring:cached
      - ./workDir/frontend/:/var/www/frontend:cached
      - ./workDir/logs/:/var/log/nginx:cached
    networks:
      - network_infrastructure
networks:
  network_infrastructure:
    name: network_infrastructure
