/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CreateLobbyRequestV1Dto } from './models/create-lobby-request-v-1-dto';
export type { CreateLobbyResponseV1Dto } from './models/create-lobby-response-v-1-dto';
