openapi: 3.0.3

info:
  title: Open Hit Game API
  version: 1.0.0

paths:
  /api/lobbies:
    post:
      summary: Create a new lobby

      requestBody:
        required: true

        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLobbyRequestV1Dto'

      responses:
        '200':
          description: Lobby created successfully

          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateLobbyResponseV1Dto'

components:
  schemas:

    CreateLobbyRequestV1Dto:
      type: object

      properties:
        playerName:
          type: string

    CreateLobbyResponseV1Dto:
      type: object

      properties:
        joinCode:
          type: string