/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateLobbyRequestV1Dto } from '../../models/create-lobby-request-v-1-dto';
import { CreateLobbyResponseV1Dto } from '../../models/create-lobby-response-v-1-dto';

export interface CreateLobby$Params {
      body: CreateLobbyRequestV1Dto
}

export function createLobby(http: HttpClient, rootUrl: string, params: CreateLobby$Params, context?: HttpContext): Observable<StrictHttpResponse<CreateLobbyResponseV1Dto>> {
  const rb = new RequestBuilder(rootUrl, createLobby.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreateLobbyResponseV1Dto>;
    })
  );
}

createLobby.PATH = '/api/lobbies';
